// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGfL9pVhooA_2SzzRBwSjLKuZ_qPa5kwA',
    appId: '1:954812172658:web:a8d4e99ffaee6a3ec235eb',
    messagingSenderId: '954812172658',
    projectId: 'fir-test-a0008',
    authDomain: 'fir-test-a0008.firebaseapp.com',
    storageBucket: 'fir-test-a0008.appspot.com',
    measurementId: 'G-47X3MXSY93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMaVKLcAqTBIUphUCn_PRCjHFNG_KysnY',
    appId: '1:954812172658:android:2676ee6befd302f5c235eb',
    messagingSenderId: '954812172658',
    projectId: 'fir-test-a0008',
    storageBucket: 'fir-test-a0008.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzdNoGOj4KIUx4HIeOYPFTDlMYHs9ssL4',
    appId: '1:954812172658:ios:29581e5689f01c3ec235eb',
    messagingSenderId: '954812172658',
    projectId: 'fir-test-a0008',
    storageBucket: 'fir-test-a0008.appspot.com',
    iosBundleId: 'com.example.edtech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzdNoGOj4KIUx4HIeOYPFTDlMYHs9ssL4',
    appId: '1:954812172658:ios:e74ba8f55589330ac235eb',
    messagingSenderId: '954812172658',
    projectId: 'fir-test-a0008',
    storageBucket: 'fir-test-a0008.appspot.com',
    iosBundleId: 'com.example.edtech.RunnerTests',
  );
}
